### ISSUE TITLE
Repo 2.0 doesn't compile anything.

### ISSUE THREAD

**Issue by Midaychi** [CptMoore/DynModLib#3]
Don't know why, but the release 2.0 on this repo doesn't manage to compile anything. The log isn't very helpful, and seems to just check some random modtek mods I have that have nothing to do with dynlib and complains about being unable to compile them, and nothing else. Doesn't even attempt to read the mods that include dynmodlib as a requirement.

The version that comes with BTMToolsWithModsPreview2cSetup.exe seems to work properly, tho.

**Comment by CptMoore** [comment]
thanks for the report, I've copied the release from my latest BTMTools release (3b on another project), hopefully it works.

**Comment by Midaychi** [comment]
3.0 Seems to function properly

**Comment by CptMoore** [comment]
thanks for the retry!
